/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Locale;
import java.util.ResourceBundle;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    private ResourceBundle bundle;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Posisikan jendela di tengah layar
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Atur jendela menjadi full screen
        setDefaultLanguage();
    }
    
    // Untuk set bahasa default ke Indonesia dan terapkan ke UI
    private void setDefaultLanguage() {
        Locale defaultLocale = new Locale("id", "ID");
        bundle = ResourceBundle.getBundle("localization.Messages", defaultLocale);
        applyLanguage();
    }
    
    // Untuk menerapkan teks UI sesuai bahasa yang dipilih dari ResourceBundle
    private void applyLanguage() {
        setTitle(bundle.getString("login.lblJudul"));
        lblJudul.setText(bundle.getString("login.lblJudul"));
        lblNamaPengguna.setText(bundle.getString("login.lblNamaPengguna"));
        lblKataSandi.setText(bundle.getString("login.lblKataSandi"));
        btnMasuk.setText(bundle.getString("login.btnMasuk"));
        lblBuatakunbaru.setText(bundle.getString("login.lblBuatAkun"));
        lblPilihBahasa.setText(bundle.getString("login.lblPilihBahasa"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblNamaPengguna = new javax.swing.JLabel();
        lblKataSandi = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        txtNamaPengguna = new javax.swing.JTextField();
        txtKataSandi = new javax.swing.JPasswordField();
        lblBuatakunbaru = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPilihBahasa = new javax.swing.JComboBox<>();
        lblPilihBahasa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(102, 102, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Masuk");

        lblNamaPengguna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNamaPengguna.setForeground(new java.awt.Color(153, 153, 153));
        lblNamaPengguna.setText("Nama Pengguna");

        lblKataSandi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKataSandi.setForeground(new java.awt.Color(153, 153, 153));
        lblKataSandi.setText("Kata sandi");

        btnMasuk.setBackground(new java.awt.Color(102, 102, 255));
        btnMasuk.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        lblBuatakunbaru.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuatakunbaru.setForeground(new java.awt.Color(0, 0, 255));
        lblBuatakunbaru.setText("Buat akun baru");
        lblBuatakunbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuatakunbaruMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblKataSandi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamaPengguna)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuatakunbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblBuatakunbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 49, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_login.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 52, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        cmbPilihBahasa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbPilihBahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "Inggris" }));
        cmbPilihBahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihBahasaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 16, 0, 20);
        jPanel1.add(cmbPilihBahasa, gridBagConstraints);

        lblPilihBahasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPilihBahasa.setForeground(new java.awt.Color(153, 153, 153));
        lblPilihBahasa.setText("Pilih Bahasa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 212, 0, 0);
        jPanel1.add(lblPilihBahasa, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Untuk ke halaman dashboard
    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        String username = txtNamaPengguna.getText();
        String password = new String(txtKataSandi.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username atau password tidak boleh kosong");
            return;
        }

        try (Connection conn = Koneksi.getConnection()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Koneksi ke database gagal.");
                return;
            }

            String sql = "SELECT id, username FROM akun WHERE username = ? AND password = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, username);
                stmt.setString(2, hashPassword(password)); // ✅ Ini wajib!

                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        String user = rs.getString("username");
                        JOptionPane.showMessageDialog(this, "Login berhasil. Selamat datang, " + user);
                        this.dispose();
                        new Dashboard().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Username atau password salah.");
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan database: " + e.getMessage());
        }
    }//GEN-LAST:event_btnMasukActionPerformed
    
    // Untuk mengganti bahasa sesuai pilihan dan terapkan ke UI
    private void cmbPilihBahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihBahasaActionPerformed
        String selected = (String) cmbPilihBahasa.getSelectedItem();
        if (selected.equals("Inggris")) {
            bundle = ResourceBundle.getBundle("localization.Messages", new Locale("en", "US"));
        } else {
            bundle = ResourceBundle.getBundle("localization.Messages", new Locale("id", "ID"));

        }
        applyLanguage();
    }//GEN-LAST:event_cmbPilihBahasaActionPerformed
    
    // Untuk menutup login dan buka form register
    private void lblBuatakunbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuatakunbaruMouseClicked
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_lblBuatakunbaruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private javax.swing.JComboBox<String> cmbPilihBahasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBuatakunbaru;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKataSandi;
    private javax.swing.JLabel lblNamaPengguna;
    private javax.swing.JLabel lblPilihBahasa;
    private javax.swing.JPasswordField txtKataSandi;
    private javax.swing.JTextField txtNamaPengguna;
    // End of variables declaration//GEN-END:variables
    // Untuk mengenkripsi password menggunakan algoritma SHA-256
    public static String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm not available", e);
        }
    }

}
